//! `melt sessions seed` — provisions credential-free demo mode.
//!
//! Resolves [KI-002](docs/internal/KNOWN_ISSUES.md). The single-file
//! DuckDB fixture lives at `var/melt/seed.ddb` and is regenerated on
//! demand from DuckDB's bundled `tpch` extension at `sf=0.01`. The
//! companion config at `melt.demo.toml` puts the proxy in seed mode
//! and points at the fixture.
//!
//! Time-budget the steps in `readme.md`'s "Quickstart (no Snowflake
//! account)" section before changing what this writes — the README
//! quickstart is the success criterion.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use clap::Subcommand;
use duckdb::Connection;

use melt_core::config::{
    SEED_ACCOUNT, SEED_DATABASE, SEED_PASSWORD, SEED_ROLE, SEED_SCHEMA, SEED_USER, SEED_WAREHOUSE,
};

#[derive(Subcommand, Debug)]
pub enum SessionsAction {
    /// Provision a self-contained demo environment — credential-free.
    /// Writes the TPC-H sf=0.01 DuckDB fixture and a `melt.demo.toml`
    /// next to the current directory. Run `melt --config melt.demo.toml all`
    /// after this to start the demo proxy.
    Seed {
        /// Re-run the dbgen step even if the fixture already exists.
        /// Useful if the schema layout in this CLI has been bumped or
        /// the file got corrupted.
        #[arg(long)]
        regenerate: bool,

        /// Path to the on-disk fixture. Default `var/melt/seed.ddb`.
        #[arg(long, default_value = "var/melt/seed.ddb")]
        fixture: PathBuf,

        /// Path to the generated demo config. Default `melt.demo.toml`.
        #[arg(long, default_value = "melt.demo.toml")]
        config: PathBuf,
    },
}

pub fn run(action: SessionsAction) -> Result<()> {
    match action {
        SessionsAction::Seed {
            regenerate,
            fixture,
            config,
        } => provision_seed(fixture, config, regenerate),
    }
}

fn provision_seed(fixture: PathBuf, config: PathBuf, regenerate: bool) -> Result<()> {
    if let Some(parent) = fixture.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating fixture parent dir {}", parent.display()))?;
    }

    let already_exists = fixture.is_file();
    if already_exists && !regenerate {
        eprintln!(
            "✓ fixture already at {} — skipping dbgen (pass --regenerate to rebuild)",
            fixture.display()
        );
    } else {
        if already_exists {
            std::fs::remove_file(&fixture)
                .with_context(|| format!("removing stale fixture {}", fixture.display()))?;
        }
        eprintln!(
            "→ generating TPC-H sf=0.01 fixture at {}",
            fixture.display()
        );
        generate_fixture(&fixture).context("generating seed.ddb")?;
        eprintln!("✓ fixture ready");
    }

    write_demo_config(&fixture, &config).context("writing demo config")?;
    eprintln!("✓ demo config at {}", config.display());

    print_next_steps(&config);
    Ok(())
}

/// Drive DuckDB's bundled `tpch` extension to produce a single-file
/// fixture at `dest`. We intentionally generate at `sf=0.01` so the
/// total fixture stays well under the 25 MB ceiling the plan
/// requested.
///
/// dbgen writes its tables into `main`. We move them into the
/// documented demo schema (`SF01`) before closing the connection so
/// the runtime ATTACH-as-`TPCH` exposes them at `TPCH.SF01.<table>`.
fn generate_fixture(dest: &Path) -> Result<()> {
    let conn = Connection::open(dest).context("open seed.ddb")?;
    conn.execute_batch("INSTALL tpch; LOAD tpch;")
        .context("INSTALL tpch")?;
    // Generate at scale factor 0.01 (~6 MB raw, comfortably under the
    // 25 MB cap once stored as DuckDB's columnar format).
    conn.execute_batch("CALL dbgen(sf = 0.01);")
        .context("CALL dbgen(sf=0.01)")?;
    let move_sql = format!(
        "CREATE SCHEMA IF NOT EXISTS {schema};
         {moves}
         ",
        schema = SEED_SCHEMA,
        moves = TPCH_TABLES
            .iter()
            .map(|t| format!(
                "CREATE TABLE {schema}.{table} AS SELECT * FROM main.{table};\n\
                 DROP TABLE main.{table};",
                schema = SEED_SCHEMA,
                table = t
            ))
            .collect::<Vec<_>>()
            .join("\n")
    );
    conn.execute_batch(&move_sql)
        .context("relocating TPC-H tables into SF01 schema")?;
    Ok(())
}

/// TPC-H tables generated by DuckDB's `dbgen` at any scale factor.
const TPCH_TABLES: &[&str] = &[
    "lineitem", "orders", "customer", "nation", "region", "part", "supplier", "partsupp",
];

/// Write `melt.demo.toml` pointing at the seed fixture. Idempotent —
/// overwrites the file every time so re-running picks up template
/// changes.
fn write_demo_config(fixture: &Path, dest: &Path) -> Result<()> {
    let body = render_demo_config(fixture);
    std::fs::write(dest, body)
        .with_context(|| format!("writing demo config to {}", dest.display()))?;
    Ok(())
}

fn render_demo_config(fixture: &Path) -> String {
    // Use the canonical SEED_* constants so anyone who edits the
    // creds in melt-core sees the demo config drift in one place.
    format!(
        r#"# Generated by `melt sessions seed`.
# Credential-free demo mode — no Snowflake account is contacted.
# See docs/SEED_MODE.md and POWA-92 for what the demo supports.

[proxy]
listen      = "127.0.0.1:8443"
tls_cert    = ""
tls_key     = ""

[sessions]
mode         = "seed"
fixture_path = "{fixture}"

# `snowflake` is required by the config schema but unused in seed
# mode. Any valid placeholder works — the proxy never contacts these
# values; `execute_passthrough` returns SeedModeUnsupported instead.
[snowflake]
account                = "{account}"
host                   = "{account}.snowflakecomputing.com"
database               = "{database}"
schema                 = "{schema}"
warehouse              = "{warehouse}"
role                   = "{role}"
auth_method            = "password"
user                   = "{user}"
password               = "{password}"

# `backend.ducklake` is also required by the config schema, but in
# seed mode the runtime skips the Postgres catalog and uses the
# single-file `LocalDuckDbBackend` instead. The values below exist
# only to satisfy the deserializer.
[backend.ducklake]
catalog_url = "postgres://demo@127.0.0.1/demo"
data_path   = "."

[router]
hybrid_execution = false
"#,
        fixture = fixture.display(),
        account = SEED_ACCOUNT,
        database = SEED_DATABASE,
        schema = SEED_SCHEMA,
        warehouse = SEED_WAREHOUSE,
        role = SEED_ROLE,
        user = SEED_USER,
        password = SEED_PASSWORD,
    )
}

fn print_next_steps(config: &Path) {
    eprintln!();
    eprintln!("Next steps:");
    eprintln!(
        "  1. cargo run -p melt-cli -- --config {} all",
        config.display()
    );
    eprintln!("  2. cd examples/python && pip install -r requirements.txt");
    eprintln!("  3. MELT_MODE=seed python melt_demo.py");
    eprintln!();
    eprintln!("Demo creds (already wired into the example):");
    eprintln!(
        "  account={} user={} password={} database={} schema={}",
        SEED_ACCOUNT, SEED_USER, SEED_PASSWORD, SEED_DATABASE, SEED_SCHEMA
    );
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn render_demo_config_includes_seed_block() {
        let body = render_demo_config(Path::new("var/melt/seed.ddb"));
        assert!(body.contains("[sessions]"));
        assert!(body.contains("mode         = \"seed\""));
        assert!(body.contains("fixture_path = \"var/melt/seed.ddb\""));
        assert!(body.contains(SEED_ACCOUNT));
        assert!(body.contains(SEED_USER));
        assert!(body.contains(SEED_DATABASE));
    }

    #[test]
    #[serial_test::serial(seed_duckdb)]
    fn provision_creates_fixture_and_config_idempotently() -> Result<()> {
        let tmp = TempDir::new()?;
        let fixture = tmp.path().join("var/melt/seed.ddb");
        let config = tmp.path().join("melt.demo.toml");

        provision_seed(fixture.clone(), config.clone(), false)?;
        assert!(fixture.is_file(), "fixture missing");
        assert!(config.is_file(), "config missing");
        let first_size = std::fs::metadata(&fixture)?.len();
        assert!(first_size > 0, "fixture is empty");
        // ≤ 25 MB hard cap from the plan.
        assert!(first_size < 25 * 1024 * 1024, "fixture grew past 25 MB cap");

        // Second run with the same args is a no-op for the fixture.
        let mtime_before = std::fs::metadata(&fixture)?.modified()?;
        provision_seed(fixture.clone(), config.clone(), false)?;
        let mtime_after = std::fs::metadata(&fixture)?.modified()?;
        assert_eq!(mtime_before, mtime_after, "no-op run rewrote fixture");

        // --regenerate rebuilds the file.
        provision_seed(fixture.clone(), config.clone(), true)?;
        assert!(fixture.is_file());
        Ok(())
    }

    #[test]
    #[serial_test::serial(seed_duckdb)]
    fn fixture_exposes_tpch_tables_in_sf01_schema() -> Result<()> {
        let tmp = TempDir::new()?;
        let fixture = tmp.path().join("seed.ddb");
        generate_fixture(&fixture)?;

        let conn = Connection::open(&fixture)?;
        let count: i64 = conn.query_row(
            "SELECT COUNT(*) FROM duckdb_tables() \
             WHERE lower(schema_name) = lower(?)",
            [SEED_SCHEMA],
            |r| r.get(0),
        )?;
        assert_eq!(
            count as usize,
            TPCH_TABLES.len(),
            "expected all TPC-H tables in {SEED_SCHEMA}"
        );
        let lineitems: i64 = conn.query_row(
            &format!("SELECT COUNT(*) FROM {SEED_SCHEMA}.lineitem"),
            [],
            |r| r.get(0),
        )?;
        assert!(lineitems > 0, "lineitem at sf=0.01 should be non-empty");
        Ok(())
    }
}
